### ISSUE TITLE
Validator signatures are broken on the most recent testnet

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#169]
* Checkout https://github.com/near/rainbow-bridge/pull/164
* Uncomment https://github.com/near/rainbow-bridge/blob/e91e1245fdb4256d87ba056bafe26c32f827678e/libs-sol/nearbridge/test/NearBridge2.js#L41
* Go to `libs-sol/nearbridge` and run `yarn test`. Observe that the uncommented test is failing, while the old tests are passing. The old tests contain blocks from the old testnet and local networks, while the new tests contains blocks from the new testnet. Something broke the verification of the signatures.

**Comment by ailisp** [comment]
We found the problem is with the data test is using. They're all from same epoch, and nearbridge doesn't have prev.next_bps, therefore unable to verify signature. If `initWithBlock` from epoch X, and `addLightClientBlock` from `epoch >= X+1` it can verify. In practice:

```
            prev.next_bps[signatureIndex].publicKey
```

is empty for the first epoch (because prev is not set until get block of second epoch), thus first epoch is not verifiable. To completely fix this prev.next_bps should be init to genesis validator sets.

**Comment by nearmax** [comment]
@ailisp Could you please add this argument to the constructor and update the relay script?
