### ISSUE TITLE
init-near-contracts tries to recreate client and prover accounts after they are created

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#229]
I am running the following command to initialize Eth2NearClient and Eth2NearProver contracts on NEAR testnet to connect to Ropsten:
```bash
node index.js init-near-contracts --near-network-id testnet --near-node-url <redacted> --eth2near-client-account eth2nearclient19 --eth2near-prover-account eth2nearprover19 --near-master-account bridge03.testnet --near-master-sk ed25519:<redacted> --eth-node-url wss://ropsten.infura.io/ws/v3/<redacted>                                                                                 
```
And I observe in wallet that the scripts successfully initializes the contract but they re-attempts initialization multiple times:
```
Batch Transaction
by @bridge03.testnet
2bdJiwc...
Failed 9m ago
New account created: @eth2nearprover19
Transferred 100 Ⓝ to @eth2nearprover19
New key added for @eth2nearprover19: ed25519:JCyBmmj...
Batch Transaction
by @bridge03.testnet
ARKdQFC...
Failed 9m ago
New account created: @eth2nearprover19
Transferred 100 Ⓝ to @eth2nearprover19
New key added for @eth2nearprover19: ed25519:JCyBmmj...
Batch Transaction
by @bridge03.testnet
4psFEud...
Succeeded 9m ago
New account created: @eth2nearprover19
Transferred 100 Ⓝ to @eth2nearprover19
New key added for @eth2nearprover19: ed25519:JCyBmmj...
Batch Transaction
by @bridge03.testnet
6KixECy...
Failed 9m ago
New account created: @eth2nearclient19
Transferred 100 Ⓝ to @eth2nearclient19
New key added for @eth2nearclient19: ed25519:JCyBmmj...
Batch Transaction
by @bridge03.testnet
95M3Up7...
Failed 9m ago
New account created: @eth2nearclient19
Transferred 100 Ⓝ to @eth2nearclient19
New key added for @eth2nearclient19: ed25519:JCyBmmj...
Batch Transaction
by @bridge03.testnet
E4LJ1N4...
Failed 9m ago
New account created: @eth2nearclient19
Transferred 100 Ⓝ to @eth2nearclient19
New key added for @eth2nearclient19: ed25519:JCyBmmj...
Batch Transaction
by @bridge03.testnet
DkzeeBT...
Succeeded 10m ago
New account created: @eth2nearclient19
Transferred 100 Ⓝ to @eth2nearclient19
New key added for @eth2nearclient19: ed25519:JCyBmmj...
```
Copy-pasted from: https://explorer.testnet.near.org/accounts/bridge03.testnet
It is possible that we are not waiting for confirmation of transaction anymore, which is problematic.

**Comment by ailisp** [comment]
This is unfortunately expected behavior due to unreliable of createAccount (which use broadcast-txn-commit): it could socket hangout, timeout or nonce but the final txn eventually success. But, we cannot get txHash of createAccount txn due to call to near-api-js throw error before it returns the txHash to us. So there's no way to know whether the txn success eventually. Right now i used a hack to treat is success when the retrying txn get response "account already exist". With this hack @nearmax would observe the txn history in explorer shown above. 
With nearprotocol/nearcore#3054 resolved fail due to nonce probably won't happen, and socket hangout & timeout is rare, so it's okay now. But I still suggest we resolve https://github.com/near/near-api-js/issues/360 to make "txn submit, but socket hangout & timeout cause we lost txHash and thus don't know tx status" issue
