### ISSUE TITLE
When NEAR blockchain has <2/3 validators the Eth2NearRelay falls back behind

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#232]
When eth-relay submits transactions to NEAR node it waits for the confirmation of this transaction, more specifically it waits for all receipts of that transaction to be executed and it waits for blocks with execution outcomes to be finalized. This is the default behavior of near-api-js that bridge is using (CC @frol , @vgrichina ). The problem is that when there are less than 2/3 of validators the blocks are not finalized immediately, which causes some transactions to take 20 seconds. This causes our Eth2NearClient to fallback behind the Ethereum chain, see the attached log: https://drive.google.com/file/d/1-6ZwgOZX--DjqncQX4V2-AlbHUSoQPt0/view?usp=sharing

Instead eth-relay should be submitting headers to Eth2NearClient optimistically using async RPC, but then checking every now and then synchronously the head of the client. Note, this mechanism need to be coupled with the currently implemented mechanism of backing off, when Ethereum node switches the fork.

**Comment by ailisp** [comment]
After some attempt, I'd argue to use a different approach to catch up: add add_blocks_many in eth-client contract. I think add (up to) 100 blocks in one txn is easier to handle than send (up to) 100 txns, each add one block. Because, in send 100 txn approach say we add block 501-600, and in them 587, 599 fails, other 98 add_block success. Then should we retry 587/599 until they success, before submit block 601, ...? And, if fork happens, retry 587,599 might be invalid, so we can't in submitBlock reschedule retry itself, because block can become fork, instead, we should record 587/599, and retry them in next loop. But again if fork happens at 587, we need resubmit block 587-600. As a result this become complicated to get correct. So i suggest  adding `add_blocks_many` in eth-client to catchup, it's in theory also faster

**Comment by nearmax** [comment]
An addition of a single block costs >100Tgas, and the gas limit is 300Tgas, so we can only add 2 blocks at a time, which is only 2x faster (which would still make Eth2NearRelay to fall back behind in some cases).

> 587, 599 fails

If 587 fails then 588, 589, etc wouldn't get accepted.

Here is what I suggest we do. Replace this code here https://github.com/near/rainbow-bridge/blob/e74f2faf9f2b32842ae54361c6f1a470ef760f42/environment/lib/eth2near-relay.js#L73-L80 with X asynchronous calls  to `add_block_header`, where X<=min(5, chainBlockNumber - clientBlockNumber), and 5 is some constant (we can pick other constant but it should not be too large or otherwise the chance of at least one call to fail will be too high). Then wait for all of them to be confirmed and proceed with the next iteration of `while(true)` loop.

**Comment by nearmax** [comment]
We can also parallelize calls to multiple `const unparsedBlock = await execute(`./vendor/ethashproof/cmd/relayer/relayer ${blockRlp} | sed -e '1,/Json output/d'`); `

**Comment by bowenwang1996** [comment]
To be clear, `broadcast_tx_commit` does not wait until the transaction is finalized. However, it may take a while for it to finish if the network is slow.

**Comment by ailisp** [comment]
> To be clear, broadcast_tx_commit does not wait until the transaction is finalized. However, it may take a while for it to finish if the network is slow.

Yeah that's accurate. we actually wrap broadcast_tx_async + tx_status until finalized together as a sync step.

**Comment by ailisp** [comment]
Based on #233 local result this is fixed, because it'll catchup by submit several blocks together (take 20s to submit up to 10 blocks).
