### ISSUE TITLE
npm package does not include contracts

### ISSUE THREAD

**Issue by nearmax** [near/rainbow-bridge#265]
As reported by @ilblackdragon our current npm package does not include the contracts as assets. We need to fix it.

**Comment by ailisp** [comment]
I think this is not unnecessary, because bundle contract alone doesn't made bridge works. Users need to run index.js prepare anyway to clone&build a ethashproof. So we should either
- package contracts and also package prebuilt ethashproof, so user doesn't need to run `index.js prepare`
- don't change current workflow. user will get contracts and ethashproof to run bridge by `index.js prepare`

**Comment by ailisp** [comment]
btw index.js is not convenient, so export it as `rbb` and published: https://github.com/near/rainbow-bridge/pull/268

**Comment by ailisp** [comment]
What are your thoughts? Also just think of `rbbr` is a good name of cli, as
- rainbow-bridge-cli is too long
- there's another npm package names rainbow-bridge, so it's good to differentiate with it
- rbbr looks like r -> b b -> r, and also short for *R*ain*B*ow*BR*idge

**Comment by Kouprin** [comment]
@ailisp rbbr sounds cool.

**Comment by ilblackdragon** [comment]
1. Name for CLI: rainbow or rainbowup?
2. See #280
3. Relayers should run independently and regular developers should not worry about it.
 E.g. regular developer flow
  3.0 clone the locker contracts repo
  3.1 (optionally) customize locker/minter contracts
  3.2 rainbow build // builds current contracts in the repo: sol & rs
  3.3 rainbow deploy '{"erc20": <erc-20 address>, "mintable-": <wanna-be-near-address>, ...other params}'

And then users can use the library can initiate transfers.

**Comment by ailisp** [comment]
> Name for CLI: rainbow or rainbowup?

We can made both or a poll. Currentlly we have both rbbr and rainbow-bridge, and I usually use rbbr since typing faster

> Relayers should run independently and regular developers should not worry about it.
 E.g. regular developer flow

It's possible in current setup, we just need a better document. Current workflow:
- `npm i -g rainbow-bridge-cli`
- create a `~/.rainbow/config.json` file, provide eth and near key, eth and near endpoints.
- (TODO, a cmd to build relayer dependency: ethashproof only, need to separate from prepare.sh which build all)
- run `rbbr start eth-relay`

We can have TODO binary packaged or build at first time they run relayer, so to user it's as easy as: install cli, set your keys in config file, start relayer.

> And then users can use the library can initiate transfers.

It's also possible with current setup, they need config.json that use our deployed contract names(near) and addresses(eth) and their keys, and run rainbow bridge transfer commands. relayers are also running by us. If they want to use their own bridge, they can run as:
1. their relayers + use our deployed contracts
2. or their relayers + they deploy contracts
Both are support by current cli.

**Comment by chadoh** [comment]
> Name for CLI

I discussed this a bit with @amgando and @potatodepaulo and we like the idea of adding two CLI commands:

1. `rainbow-bridge-cli` – exactly match the package name, so I don’t have to guess. I can `npm i -g rainbow-bridge-cli` and then immediately know that I can use the same name to run commands
2. `rain` – more memorable & meme-able than `rbbr`, which looks like `rubber`. Rain ETH into NEAR! This will be the main command that people use. Four letters ain’t bad.
3. `🌈` – bonus command! Why not also provide the single-character rainbow emoji as an alias? Maybe not convenient for many people to type, but will look great in tweets 😄

**Comment by ailisp** [comment]
Currently it's by design not include contracts (it needs to clone/build contracts and ethashproof binary), and we discussed future plans will be package contracts as separated npm package, at that time contracts will be auto included because of npm dependencies
