### ISSUE TITLE
GasLimitExceeded on recent transactions

### ISSUE THREAD

**Issue by frol** [near/rainbow-bridge#332]
https://explorer.testnet.near.org/transactions/3oW9Kjnas1J4MGzFKStpHVj1SSuMMSJ244bDxVNaWLHD

**Comment by ailisp** [comment]
Why this exceed gas limit? From explorer it attached 300T gas but only used 205T :thinking:

**Comment by nearmax** [comment]
> Why this exceed gas limit? From explorer it attached 300T gas but only used 205T 🤔

300Tgas is the max attached gas. 200Tgas is the limit per single contract execution.

**Comment by nearmax** [comment]
At first I thought it is related to super deep reorgs see https://github.com/near/rainbow-bridge-cli/issues/329 <https://github.com/near/rainbow-bridge-cli/issues/329>, because I haven’t analyzed the contract on the subject of super deep re-orgs. However, Ropsten did no undergo deep reorgs in the past few days.

I suspect either of the following happened:
* `add_block_header` is not O(1), maybe also because of some unknown bug in `UnorderedMap`. Because this specific client was launched with `finalized_gc_threshold=30k` the issue has surfaced;
* Since Ropsten is unstable we could’ve received a malformed header;

**Comment by nearmax** [comment]
Assigning to @abacabadabacaba since he is auditing our contracts.

**Comment by djsatok** [comment]
Closed with #479
